### ISSUE TITLE
Allow committing to master & develop (?)

### ISSUE THREAD

**Issue by yurtsiv** [jessedobbelaere/jira-smart-commit#39]
Hi,

I noticed that the hook does not allow committing directly to `master` and `develop`.

It's completely fine for me, but there's two things:
1) Not all people have the same Git workflow. For someone it's ok to commit minor fixes to `master`/`develop`  
2) The message says `Please set up a PR to 'master' from GitHub and merge from there`, but not everyone uses GitHub. I use Bitbucket f.e.

I know it can be bypassed with `--no-verify` flag, but this kind of check is not in the scope of this hook IMHO.
So I'd rather remove this check or at least make the error message more general.

What do you think? I Will be happy to create a PR.

And thanks for creating this cute little package, it's really helpful!

**Comment by jessedobbelaere** [comment]
hi @yurtsiv ! Thanks for that remark. This package started at my workplace to always have smart commits and no direct commits on master. Although nowadays "protected branches" fix that too. And you're right: in 2020, people started moving away from the `master` naming convention since it could be offensive, so the term `main` branch is popular now too.

The error message mentioning Github also needs to update indeed. We move to Gitlab for example :-) 

Feel free to create a pull request to allow these things to be configured or disabled 🙌  Or we can remove that "forbidden branches" part entirely from the code and suggest to solve it with [Protected Branches](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-protected-branches)

**Comment by yurtsiv** [comment]
@jessedobbelaere PR is ready, let me know what you think.

**Comment by jessedobbelaere** [comment]
Thanks! I released v1.1.2 🎉
